AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.graphqlHander
      Runtime: nodejs8.10
      Role: arn:aws:iam::435716529842:role/LambdaDynamo
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
  GoodreadsSync:
    Type: AWS::Serverless::Function
    Environment:
      Variables:
        GOODREADS_KEY: '{{resolve:ssm:GOODREADS_KEY:1}}'
        GOODREADS_USER: '{{resolve:ssm:GOODREADS_USER:1}}'
    Properties:
      Handler: index.goodreadsHandler
      Runtime: nodejs8.10
      Role: arn:aws:iam::435716529842:role/LambdaDynamo
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /goodreads
            Method: ANY
