AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: graphql/index.handler
      Runtime: nodejs8.10
      Role: arn:aws:iam::435716529842:role/LambdaDynamo
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
  GoodreadsSync:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          GOODREADS_KEY: '{{resolve:secretsmanager:GoodreadsData:SecretString:GOODREADS_KEY}}'
          GOODREADS_USER: '38789987'
      Handler: goodreads/index.handler
      Runtime: nodejs8.10
      Role: arn:aws:iam::435716529842:role/LambdaDynamo
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /goodreads
            Method: ANY
  # GoodreadsCron:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     ScheduleExpression: cron(00 04 * * * ? *)
  #     Targets:
  #       - Arn:
  #           Fn:GetAtt: [GoodreadsSync, 'Arn']
  #           Id:
  #             Ref: GoodreadsSync
  # LambdaInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName:
  #       Fn::GetAtt: [GoodreadsSync, "Arn"]
  #     Action: lambda:InvokeFunction
  #     Principal: events.amazonaws.com
  #     SourceArn:
  #       Fn::GetAtt: [GoodreadsSync, "Arn"]
