export const ReReads = [
  {
    'Book Id': 93050,
    Title: 'Anna Karenina',
    Author: 'Leo Tolstoy',
    'Author l-f': 'Tolstoy, Leo',
    'Additional Authors': 'Louise Maude, Aylmer Maude, John Bayley',
    ISBN: '="9780679410003',
    ISBN13: '="9780679410003',
    'My Rating': 5,
    'Average Rating': 4.04,
    Publisher: "Everyman's Library",
    Binding: 'Hardcover',
    'Number of Pages': 1016,
    'Year Published': 1992,
    'Original Publication Year': 1877,
    'Date Read': '2019/03/03',
    'Date Added': '2015/07/13',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 2,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: ''
  },
  {
    'Book Id': 33512527,
    Title: 'Till We Have Faces: A Myth Retold',
    Author: 'C.S. Lewis',
    'Author l-f': 'Lewis, C.S.',
    'Additional Authors': '',
    ISBN: '="0062565419',
    ISBN13: '="',
    'My Rating': 5,
    'Average Rating': 4.19,
    Publisher: 'HarperOne',
    Binding: 'Kindle Edition',
    'Number of Pages': 368,
    'Year Published': 2017,
    'Original Publication Year': 1956,
    'Date Read': '2019/08/17',
    'Date Added': '2015/01/26',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 2,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: ''
  }
]
