export const books2018 = [
  {
    'Book Id': 82692,
    Title: 'repellat aut commodi',
    Author: 'Minnie Schumm',
    'Author l-f': 'Schumm, Minnie',
    'Additional Authors': "Mia O'Hara",
    ISBN: '="0812992989"',
    ISBN13: 72155,
    'My Rating': 1,
    'Average Rating': 4,
    Publisher: 'Schaefer Inc',
    Binding: 'voluptate',
    'Number of Pages': 59813,
    'Year Published': '1983',
    'Original Publication Year': '2009',
    'Date Read': '2018/08/06',
    'Date Added': '2019-01-02',
    Bookshelves: 'quo',
    'Bookshelves with positions': 'nihil',
    'Exclusive Shelf': 'voluptates',
    'My Review':
      'Animi corrupti deserunt minima. Deleniti et perspiciatis nisi. Aut et dolor id ipsa fuga laborum nobis consequuntur magnam. Magni enim perferendis perspiciatis. Sunt dolor beatae vitae magni consectetur deserunt odit eum.',
    Spoiler:
      'Qui impedit excepturi doloremque ipsum id sunt. Quia quia facere culpa tenetur eos. Ut maxime ea inventore vitae labore in. Quo ratione architecto omnis culpa fuga voluptate non illum maxime. Velit porro velit libero et consequatur laborum qui omnis aliquam. Assumenda id voluptatem voluptates quas tempore nulla ea.',
    'Private Notes':
      'Sint pariatur et sunt. Suscipit atque et odit autem nulla nam voluptatum sunt. Ab excepturi repudiandae voluptatem. Molestias possimus omnis optio doloribus vero nemo dolor dolor impedit. Eligendi similique adipisci et molestiae. Aut quo in assumenda magni quisquam asperiores.',
    'Read Count': 17249,
    'Recommended For': 'Willy Nolan',
    'Recommended By': 'Lilian Cremin PhD',
    'Owned Copies': 24014,
    'Original Purchase Date': '2018-12-02',
    'Original Purchase Location': 'Oberbrunner and Sons',
    Condition: 'eum',
    'Condition Description':
      'Exercitationem pariatur cumque ea asperiores ipsam sed.',
    BCID: 72511
  },
  {
    'Book Id': 91348,
    Title: 'ad consequuntur quo',
    Author: 'Carlotta Morissette',
    'Author l-f': 'Morissette, Carlotta',
    'Additional Authors': 'Jacynthe Ward',
    ISBN: '="0812992989"',
    ISBN13: 4361,
    'My Rating': 2,
    'Average Rating': 1,
    Publisher: 'Lebsack and Sons',
    Binding: 'aspernatur',
    'Number of Pages': 14694,
    'Year Published': '2004',
    'Original Publication Year': '2013',
    'Date Read': '2018/08/06',
    'Date Added': '2018-11-02',
    Bookshelves: 'voluptas',
    'Bookshelves with positions': 'veniam',
    'Exclusive Shelf': 'ducimus',
    'My Review':
      'Temporibus facilis aliquid reiciendis. Alias iste quia ex quibusdam dolores esse magnam. Enim harum voluptatibus libero aspernatur qui vel officia. Ab qui qui.',
    Spoiler:
      'Facilis nam autem asperiores porro blanditiis nobis. Iste officia est provident. Ut dolores quis voluptatum ut quis accusantium. Ut facilis consequatur excepturi qui mollitia incidunt in est tenetur.',
    'Private Notes':
      'Omnis itaque voluptas quod et harum dolores debitis doloribus. Sed totam tempora provident aut excepturi perspiciatis. Incidunt quibusdam quisquam neque quo voluptatem qui corporis error. Quo ducimus rerum omnis omnis quo sequi.',
    'Read Count': 52382,
    'Recommended For': 'Rebeka Grady',
    'Recommended By': 'Mr. Devonte Price',
    'Owned Copies': 79514,
    'Original Purchase Date': '2018-10-02',
    'Original Purchase Location': 'Thiel and Sons',
    Condition: 'mollitia',
    'Condition Description': 'Vel qui earum perspiciatis sunt incidunt enim.',
    BCID: 87765
  },
  {
    'Book Id': 87148,
    Title: 'at incidunt distinctio',
    Author: 'Julio Kozey',
    'Author l-f': 'Kozey, Julio',
    'Additional Authors': 'Conner Wolff DDS',
    ISBN: '="0812992989"',
    ISBN13: 18622,
    'My Rating': 3,
    'Average Rating': 4,
    Publisher: 'Gleichner, Casper and Runolfsdottir',
    Binding: 'aut',
    'Number of Pages': 70736,
    'Year Published': '1997',
    'Original Publication Year': '1988',
    'Date Read': '2018/08/06',
    'Date Added': '2018-11-02',
    Bookshelves: 'suscipit',
    'Bookshelves with positions': 'et',
    'Exclusive Shelf': 'sit',
    'My Review':
      'Officia occaecati quibusdam vitae molestias iusto suscipit eos. Ducimus ullam fuga minus perspiciatis voluptatem accusamus atque. Provident voluptatem deleniti itaque a quae qui voluptate. Corrupti numquam velit consequatur ea possimus blanditiis.',
    Spoiler:
      'Iste velit nihil iusto. Quo qui cum dolorum quaerat aut corrupti qui. Ut molestias modi tempore necessitatibus illo. Eveniet consectetur ullam sed voluptas.',
    'Private Notes':
      'Soluta in voluptas molestias. Dolorem consequatur amet recusandae aut amet in non odit facilis. Dolor odit sint distinctio at iure possimus modi nobis. Molestias facilis voluptates quae reiciendis. Fuga occaecati dignissimos aut.',
    'Read Count': 23495,
    'Recommended For': 'Teagan Turner',
    'Recommended By': 'Mary Botsford',
    'Owned Copies': 75746,
    'Original Purchase Date': '2018-12-02',
    'Original Purchase Location': 'Langworth Inc',
    Condition: 'voluptas',
    'Condition Description':
      'Ut labore ut magni quam dolorem enim adipisci numquam reiciendis.',
    BCID: 3561
  },
  {
    'Book Id': 98263,
    Title: 'nihil esse voluptatibus',
    Author: 'Celestine Klocko',
    'Author l-f': 'Klocko, Celestine',
    'Additional Authors': 'Demarcus Jones',
    ISBN: '="0812992989"',
    ISBN13: 75629,
    'My Rating': 4,
    'Average Rating': 2,
    Publisher: 'Hirthe - Will',
    Binding: 'aut',
    'Number of Pages': 58159,
    'Year Published': '2003',
    'Original Publication Year': '2016',
    'Date Read': '2018/08/06',
    'Date Added': '2018-11-02',
    Bookshelves: 'deserunt',
    'Bookshelves with positions': 'reiciendis',
    'Exclusive Shelf': 'nesciunt',
    'My Review':
      'Inventore ipsum quidem. Quasi maiores sed voluptatem tenetur. Aut quasi ad amet corrupti occaecati cupiditate officia quo molestiae.',
    Spoiler:
      'Exercitationem suscipit impedit tenetur. Ex et quia et beatae vitae fugit expedita. Vel et commodi sint et natus iusto suscipit inventore et. Molestiae voluptate laboriosam dolorem velit culpa quas nihil quia. Ex voluptatem culpa voluptas fuga aut.',
    'Private Notes':
      'Molestias consequatur omnis dolores a ullam. Recusandae rerum maxime et maiores voluptas assumenda ex maiores quia. Dolor modi officia nemo minima est error praesentium exercitationem nobis.',
    'Read Count': 24580,
    'Recommended For': 'Danielle Kris DDS',
    'Recommended By': 'Jerel Kiehn',
    'Owned Copies': 70853,
    'Original Purchase Date': '2019-01-02',
    'Original Purchase Location': 'Ward - Auer',
    Condition: 'autem',
    'Condition Description':
      'In quia repellendus in aut omnis velit minima aut velit.',
    BCID: 40484
  },
  {
    'Book Id': 30782,
    Title: 'magni reiciendis sed',
    Author: 'Sammy Shanahan',
    'Author l-f': 'Shanahan, Sammy',
    'Additional Authors': "Dedrick O'Hara",
    ISBN: '="0812992989"',
    ISBN13: 18872,
    'My Rating': 5,
    'Average Rating': 4,
    Publisher: 'Toy LLC',
    Binding: 'sit',
    'Number of Pages': 11651,
    'Year Published': '1985',
    'Original Publication Year': '2012',
    'Date Read': '2018/08/06',
    'Date Added': '2019-03-02',
    Bookshelves: 'repellendus',
    'Bookshelves with positions': 'excepturi',
    'Exclusive Shelf': 'maiores',
    'My Review':
      'Voluptate sed id non pariatur saepe molestias id earum. Id aperiam alias placeat ut neque unde nostrum nesciunt deserunt. Vel omnis laudantium quisquam expedita eius totam. Totam enim facilis ut est autem.',
    Spoiler:
      'Temporibus laborum modi maxime. Deserunt maxime qui ullam. Beatae reprehenderit fugit numquam incidunt dignissimos. Ipsum consequuntur iste nostrum facilis nihil rerum. Consectetur excepturi molestiae ea ut aut est saepe incidunt.',
    'Private Notes':
      'Commodi voluptatem deserunt nostrum deserunt aperiam sed aspernatur voluptatem. Nam nobis adipisci velit eligendi id repudiandae et. In est blanditiis illo voluptate in ut. Delectus nesciunt voluptas minima et laudantium facilis enim.',
    'Read Count': 94476,
    'Recommended For': 'Isom Donnelly',
    'Recommended By': 'Genevieve Turner',
    'Owned Copies': 10997,
    'Original Purchase Date': '2018-12-02',
    'Original Purchase Location': 'Willms and Sons',
    Condition: 'eveniet',
    'Condition Description': 'Ut laudantium et dolorem.',
    BCID: 16453
  }
]

export const books2017 = [
  {
    'Book Id': 49164,
    Title: 'earum repellendus qui',
    Author: 'Clementina Beahan',
    'Author l-f': 'Beahan, Clementina',
    'Additional Authors': 'Columbus Steuber',
    ISBN: '="0812992989"',
    ISBN13: 62495,
    'My Rating': 1,
    'Average Rating': 1,
    Publisher: 'McLaughlin - Ward',
    Binding: 'et',
    'Number of Pages': 75390,
    'Year Published': '2012',
    'Original Publication Year': '2019',
    'Date Read': '2017/08/06',
    'Date Added': '2019-02-02',
    Bookshelves: 'eos',
    'Bookshelves with positions': 'illo',
    'Exclusive Shelf': 'esse',
    'My Review':
      'Suscipit sint perspiciatis maiores autem ad sed necessitatibus facilis sapiente. Exercitationem vel sequi laboriosam ducimus quia molestiae magni qui. Esse soluta et occaecati dolores et consequuntur modi blanditiis quas. Qui voluptatem quaerat perspiciatis dolorem totam laboriosam pariatur vel. Culpa occaecati ex veniam sint ut quo.',
    Spoiler:
      'Ducimus ut odio atque atque amet est. Ut in vel ut ex asperiores necessitatibus pariatur excepturi. Facere esse fuga consectetur. Exercitationem molestiae est sit placeat et quia pariatur assumenda. A ea quia earum fugiat qui. Reprehenderit suscipit enim aperiam.',
    'Private Notes':
      'Eaque neque ut voluptas excepturi delectus quidem. Est cumque similique qui omnis facilis id voluptatum odio. Rerum dolore provident. Qui mollitia praesentium qui rem qui nobis sunt nisi. Magnam quo excepturi dolorem repellendus dicta reprehenderit quam culpa.',
    'Read Count': 40271,
    'Recommended For': 'Rosella Dickinson',
    'Recommended By': 'Jules Turcotte',
    'Owned Copies': 47889,
    'Original Purchase Date': '2018-12-02',
    'Original Purchase Location': "Rodriguez, Pollich and O'Keefe",
    Condition: 'et',
    'Condition Description':
      'Suscipit quam nisi rerum aperiam doloremque voluptas expedita.',
    BCID: 2681
  },
  {
    'Book Id': 1107,
    Title: 'quo aliquid earum',
    Author: 'Amy Weber',
    'Author l-f': 'Weber, Amy',
    'Additional Authors': 'Veda Dickens',
    ISBN: '="0812992989"',
    ISBN13: 20769,
    'My Rating': 2,
    'Average Rating': 0,
    Publisher: 'Prosacco Group',
    Binding: 'voluptatibus',
    'Number of Pages': 7470,
    'Year Published': '1992',
    'Original Publication Year': '1991',
    'Date Read': '2017/08/06',
    'Date Added': '2019-02-02',
    Bookshelves: 'ullam',
    'Bookshelves with positions': 'quia',
    'Exclusive Shelf': 'harum',
    'My Review':
      'Unde in placeat et totam adipisci quis. Nisi et eligendi labore alias voluptatem. Assumenda in in sunt sint. Non delectus aspernatur expedita quam. Inventore debitis quibusdam enim a quisquam.',
    Spoiler:
      'Ab fugiat aliquam rerum voluptatem commodi qui minima. Similique provident architecto iure et dolorum officiis. Qui ab officiis nesciunt ut recusandae perferendis. Nemo quam dolore.',
    'Private Notes':
      'Distinctio perspiciatis eos occaecati quibusdam. Dignissimos ad et qui voluptatem. Ea totam inventore nam vel eligendi temporibus. Eos harum consequuntur quia suscipit. Quam enim dignissimos fugit non et ea.',
    'Read Count': 72268,
    'Recommended For': 'Allen Hand',
    'Recommended By': 'Iliana Yost',
    'Owned Copies': 33634,
    'Original Purchase Date': '2018-11-02',
    'Original Purchase Location': 'Morar, Collins and Koch',
    Condition: 'qui',
    'Condition Description':
      'Qui ipsum provident voluptatum temporibus odit cum architecto ut et.',
    BCID: 38802
  },
  {
    'Book Id': 55985,
    Title: 'sed omnis sunt',
    Author: 'Evan Wisoky',
    'Author l-f': 'Wisoky, Evan',
    'Additional Authors': 'Miss Domenico Hoeger',
    ISBN: '="0812992989"',
    ISBN13: 32892,
    'My Rating': 3,
    'Average Rating': 5,
    Publisher: 'Sanford, Rowe and Rath',
    Binding: 'doloremque',
    'Number of Pages': 37716,
    'Year Published': '1996',
    'Original Publication Year': '1987',
    'Date Read': '2017/08/06',
    'Date Added': '2019-01-02',
    Bookshelves: 'molestiae',
    'Bookshelves with positions': 'itaque',
    'Exclusive Shelf': 'ut',
    'My Review':
      'Quasi iure suscipit dicta fugit mollitia voluptatem nihil quidem perspiciatis. Quo reiciendis sit autem nihil explicabo molestiae id. Neque sed sit. Mollitia quasi mollitia vitae excepturi quibusdam. Aut voluptatem nemo. Quis occaecati debitis et ad.',
    Spoiler:
      'Qui harum fugiat placeat nam vitae dolorum. Non ut neque nesciunt velit. Et natus et voluptas et et hic. Et sed quia molestiae porro nihil et quo. Rerum neque non.',
    'Private Notes':
      'Nobis fugiat facilis dicta numquam nisi et voluptas. Eum laboriosam aspernatur fugit repellat accusamus ratione quia. Quas occaecati architecto animi. Iusto alias excepturi eligendi eum ducimus a eos incidunt. Consequatur officia id ut nemo.',
    'Read Count': 33123,
    'Recommended For': 'Shawn Robel',
    'Recommended By': 'Ezequiel Ruecker',
    'Owned Copies': 22340,
    'Original Purchase Date': '2018-11-02',
    'Original Purchase Location': 'Wolff - Graham',
    Condition: 'quia',
    'Condition Description': 'Officiis non et eveniet fuga id.',
    BCID: 8116
  },
  {
    'Book Id': 4506,
    Title: 'molestias libero incidunt',
    Author: 'Wellington Grant DDS',
    'Author l-f': 'DDS, Grant, Wellington',
    'Additional Authors': "Mrs. Elton O'Hara",
    ISBN: '="0812992989"',
    ISBN13: 32438,
    'My Rating': 4,
    'Average Rating': 1,
    Publisher: 'Beer Group',
    Binding: 'dolor',
    'Number of Pages': 90553,
    'Year Published': '1988',
    'Original Publication Year': '2008',
    'Date Read': '2017/08/06',
    'Date Added': '2019-01-02',
    Bookshelves: 'et',
    'Bookshelves with positions': 'dignissimos',
    'Exclusive Shelf': 'soluta',
    'My Review':
      'Rerum aut omnis. Nam est expedita velit quos eos ut est. Et provident non porro sunt porro. Autem velit odit repudiandae qui. Enim sed culpa. Exercitationem consequatur qui sed quo minima occaecati labore ut.',
    Spoiler:
      'Debitis libero neque dolorum sed aut aspernatur atque. Error et nobis dolorum eos ut esse ut. Et voluptatibus voluptas iure consequatur consequatur excepturi aut dolor. Et qui dolorem velit. Magni iste qui perspiciatis.',
    'Private Notes':
      'Minus in iste et mollitia ut vel dicta et soluta. Magnam et consectetur necessitatibus sunt excepturi enim. Perspiciatis sint distinctio necessitatibus alias illo quis repellat. Necessitatibus et minus non dolorum aut aperiam. Repudiandae qui quae dignissimos.',
    'Read Count': 38979,
    'Recommended For': 'Carleton Powlowski',
    'Recommended By': 'Dillon Lang',
    'Owned Copies': 65840,
    'Original Purchase Date': '2018-10-02',
    'Original Purchase Location': 'Kovacek LLC',
    Condition: 'sit',
    'Condition Description': 'Aliquid et asperiores minima atque voluptatem.',
    BCID: 60373
  },
  {
    'Book Id': 42497,
    Title: 'doloribus facilis quia',
    Author: 'Shaina Schaefer',
    'Author l-f': 'Schaefer, Shaina',
    'Additional Authors': 'Taurean Osinski',
    ISBN: '="0812992989"',
    ISBN13: 89910,
    'My Rating': 5,
    'Average Rating': 2,
    Publisher: 'Boyer - Toy',
    Binding: 'fuga',
    'Number of Pages': 59784,
    'Year Published': '2009',
    'Original Publication Year': '2014',
    'Date Read': '2017/08/06',
    'Date Added': '2019-02-02',
    Bookshelves: 'corrupti',
    'Bookshelves with positions': 'accusantium',
    'Exclusive Shelf': 'exercitationem',
    'My Review':
      'Voluptatem tempora voluptatem quisquam aut quae. Qui voluptatum quia. Deleniti delectus porro vel dolorum exercitationem molestiae quia.',
    Spoiler:
      'Accusantium necessitatibus modi repudiandae rerum in est laborum autem cupiditate. Officia et esse officia labore. Nulla et quis dolor expedita saepe harum ea quaerat. Aut sed qui voluptatem laboriosam molestiae non non placeat. Et perferendis et non omnis tenetur qui quas possimus.',
    'Private Notes':
      'Ea culpa et. Iure delectus aliquid similique provident sit qui sint. Dicta et voluptatibus non officiis qui. Neque impedit doloremque eos totam non nobis amet.',
    'Read Count': 58676,
    'Recommended For': 'Kurtis Flatley Sr.',
    'Recommended By': 'Dr. Ned Weissnat',
    'Owned Copies': 89888,
    'Original Purchase Date': '2019-03-02',
    'Original Purchase Location': 'Rohan Group',
    Condition: 'voluptatum',
    'Condition Description': 'Ut architecto consequatur ad veniam voluptas.',
    BCID: 56517
  }
]

export const books2016 = [
  {
    'Book Id': 16368,
    Title: 'atque numquam aspernatur',
    Author: 'Eudora Hartmann',
    'Author l-f': 'Hartmann, Eudora',
    'Additional Authors': 'Foster Hudson',
    ISBN: '="0812992989"',
    ISBN13: 25138,
    'My Rating': 1,
    'Average Rating': 3,
    Publisher: 'Medhurst - Roberts',
    Binding: 'commodi',
    'Number of Pages': 80138,
    'Year Published': '1990',
    'Original Publication Year': '2000',
    'Date Read': '2016/08/06',
    'Date Added': '2019-02-02',
    Bookshelves: 'non',
    'Bookshelves with positions': 'et',
    'Exclusive Shelf': 'ab',
    'My Review':
      'Soluta odio quia modi odit quia et quia exercitationem. Repellendus et velit neque aut. Et ex enim voluptates quo sapiente consequuntur aut sit. Reiciendis reiciendis aliquam deleniti dolores eos. Iusto enim ipsa molestias sit molestiae. Adipisci esse et laborum.',
    Spoiler:
      'Repellat id enim velit consequatur aut non. Unde eaque sequi. Quia sit fugiat explicabo magnam nostrum vel soluta illum. Doloremque libero ipsum blanditiis et blanditiis omnis eum sit dicta. Necessitatibus explicabo eum voluptatem porro eum nihil id.',
    'Private Notes':
      'Quia sequi qui. Perferendis ut molestias culpa. Praesentium et sunt qui quis aut. Qui eveniet earum fugit ut fugit maiores mollitia quidem corporis.',
    'Read Count': 15922,
    'Recommended For': 'Cielo Toy I',
    'Recommended By': 'Quinten Lakin',
    'Owned Copies': 31997,
    'Original Purchase Date': '2019-03-02',
    'Original Purchase Location': 'Hermann Inc',
    Condition: 'harum',
    'Condition Description': 'Minima est voluptatem eius occaecati explicabo.',
    BCID: 60798
  },
  {
    'Book Id': 27731,
    Title: 'reprehenderit enim saepe',
    Author: 'Maegan Cassin Jr.',
    'Author l-f': 'Jr., Cassin, Maegan',
    'Additional Authors': 'Vivienne Hackett',
    ISBN: '="0812992989"',
    ISBN13: 66161,
    'My Rating': 2,
    'Average Rating': 5,
    Publisher: 'Murray LLC',
    Binding: 'aut',
    'Number of Pages': 66634,
    'Year Published': '2006',
    'Original Publication Year': '1998',
    'Date Read': '2016/08/06',
    'Date Added': '2019-01-02',
    Bookshelves: 'quaerat',
    'Bookshelves with positions': 'vitae',
    'Exclusive Shelf': 'doloremque',
    'My Review':
      'Id aliquam voluptatum culpa facere. Quibusdam vel nesciunt quam accusamus. Est sed ea. Aut omnis at dolorem. Quia temporibus molestias at. Odio impedit veniam odio qui sunt eum.',
    Spoiler:
      'Qui corrupti odit nihil unde. Aut doloribus expedita. Dicta modi sequi expedita a quo vel architecto. Laudantium quo et porro commodi illo illum quia voluptatum. Maxime sequi explicabo nam illo at et quibusdam culpa nemo.',
    'Private Notes':
      'Dolores mollitia rerum odit est itaque rerum quia praesentium. Pariatur expedita possimus non qui amet. Itaque in adipisci quos facilis laudantium. Aliquid distinctio unde inventore consequatur inventore. Esse aut molestiae praesentium autem qui veritatis est. Pariatur suscipit culpa aut iusto distinctio culpa.',
    'Read Count': 27442,
    'Recommended For': 'Leta Bergstrom',
    'Recommended By': 'Aaliyah Lockman',
    'Owned Copies': 26195,
    'Original Purchase Date': '2019-03-02',
    'Original Purchase Location': 'Heidenreich - Becker',
    Condition: 'quas',
    'Condition Description':
      'Beatae magni voluptatem ea id voluptatem error perferendis qui.',
    BCID: 83507
  },
  {
    'Book Id': 65893,
    Title: 'exercitationem maiores repellat',
    Author: 'Chaim Rodriguez',
    'Author l-f': 'Rodriguez, Chaim',
    'Additional Authors': 'Ryley Gusikowski',
    ISBN: '="0812992989"',
    ISBN13: 68081,
    'My Rating': 3,
    'Average Rating': 5,
    Publisher: 'Gibson - Prosacco',
    Binding: 'vitae',
    'Number of Pages': 69613,
    'Year Published': '1998',
    'Original Publication Year': '2012',
    'Date Read': '2016/08/06',
    'Date Added': '2019-01-02',
    Bookshelves: 'et',
    'Bookshelves with positions': 'iste',
    'Exclusive Shelf': 'officiis',
    'My Review':
      'Ipsa amet et consectetur fugiat praesentium. Facere fuga et velit deserunt. Sit architecto ullam unde. Tempora id culpa. Architecto hic qui cupiditate voluptatem natus ut consequuntur quasi.',
    Spoiler:
      'Sunt ratione itaque nisi sapiente aut repellendus aut illum. Nihil provident quasi qui placeat ab minus. Veritatis est accusantium voluptates eum impedit sit modi. Harum repellendus inventore officia asperiores. Laboriosam nam ab quisquam quisquam.',
    'Private Notes':
      'Sequi voluptas sunt suscipit dignissimos praesentium odio eos est. Rerum excepturi nihil. Eaque aut et sed officiis. Nihil nihil aut. Labore qui nesciunt.',
    'Read Count': 90535,
    'Recommended For': 'Jasmin Carter Sr.',
    'Recommended By': 'Delpha Harber',
    'Owned Copies': 40505,
    'Original Purchase Date': '2019-03-02',
    'Original Purchase Location': 'Streich Inc',
    Condition: 'doloribus',
    'Condition Description':
      'Autem ipsam nesciunt quia et fugiat qui omnis impedit.',
    BCID: 63016
  },
  {
    'Book Id': 86356,
    Title: 'est eligendi aut',
    Author: 'Hiram Brekke',
    'Author l-f': 'Brekke, Hiram',
    'Additional Authors': 'Gaylord Schumm',
    ISBN: '="0812992989"',
    ISBN13: 92387,
    'My Rating': 4,
    'Average Rating': 2,
    Publisher: 'Moen Group',
    Binding: 'ipsam',
    'Number of Pages': 18317,
    'Year Published': '1988',
    'Original Publication Year': '2006',
    'Date Read': '2016/08/06',
    'Date Added': '2019-03-02',
    Bookshelves: 'ex',
    'Bookshelves with positions': 'labore',
    'Exclusive Shelf': 'officia',
    'My Review':
      'Esse totam deleniti exercitationem eum quidem eveniet rerum. Aliquid quis quos. Eveniet dolorem qui perferendis ex. Quae quia id dolorem dolor dignissimos iste.',
    Spoiler:
      'Nemo nobis sint facilis dolor dolor ea odit et. Voluptates sit omnis architecto ut. Perferendis asperiores autem eos consectetur molestias quaerat at nam atque. Qui consequatur et iste numquam possimus incidunt aperiam delectus doloribus. Voluptas excepturi qui et repellat.',
    'Private Notes':
      'Sapiente enim suscipit. Eaque dolor quaerat quia. Nostrum voluptas optio porro. Officia atque beatae a temporibus cumque. Qui impedit ipsum dolorem dolore aperiam itaque.',
    'Read Count': 89383,
    'Recommended For': 'Vernie Buckridge',
    'Recommended By': 'Mr. Jaylon Schamberger',
    'Owned Copies': 21739,
    'Original Purchase Date': '2019-02-02',
    'Original Purchase Location': 'Hane, Kunde and McGlynn',
    Condition: 'totam',
    'Condition Description': 'Amet ut voluptas fugit repellendus.',
    BCID: 60915
  },
  {
    'Book Id': 11449,
    Title: 'nesciunt architecto a',
    Author: 'Marques Nolan',
    'Author l-f': 'Nolan, Marques',
    'Additional Authors': 'Lindsay Bechtelar',
    ISBN: '="0812992989"',
    ISBN13: 66021,
    'My Rating': 5,
    'Average Rating': 2,
    Publisher: 'Kuhlman and Sons',
    Binding: 'impedit',
    'Number of Pages': 74956,
    'Year Published': '1998',
    'Original Publication Year': '2009',
    'Date Read': '2016/08/06',
    'Date Added': '2019-02-02',
    Bookshelves: 'saepe',
    'Bookshelves with positions': 'culpa',
    'Exclusive Shelf': 'qui',
    'My Review':
      'Dolore commodi illum sequi dolor et. Est nulla dolorum et. Magni quo repudiandae quam atque. Magnam earum est earum iure voluptatem nisi iusto repudiandae.',
    Spoiler:
      'Aut molestiae pariatur nisi omnis nobis rerum. Aliquid cupiditate placeat autem. Dicta nemo voluptatem rerum ut et maxime. Nulla eveniet dolore animi quia quam eum. Ex et vitae vel. Labore illum sit.',
    'Private Notes':
      'Libero totam quas itaque temporibus omnis facilis suscipit atque consequatur. Magni natus minima minus sequi quo sed cum voluptate. Atque ut enim neque consectetur. Dolores rerum sed consequatur quae animi ea quas nostrum. Quidem rerum ipsum tempora distinctio dolor quibusdam placeat.',
    'Read Count': 43655,
    'Recommended For': 'Carmela Hahn',
    'Recommended By': 'Joan Ebert',
    'Owned Copies': 61212,
    'Original Purchase Date': '2019-02-02',
    'Original Purchase Location': 'Bayer - Zulauf',
    Condition: 'quasi',
    'Condition Description': 'Consequatur nihil quia est sit.',
    BCID: 7087
  }
]

export const mockBooks = [...books2018, ...books2017, ...books2016]
